apiVersion: v1
kind: Service
metadata:
  name: psql-svc
  labels:
    app: kumar-psql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:     
    app: kumar-psql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: kumar-psql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kumar-psql
  template:
    metadata:
      labels:
        app: kumar-psql
    spec:
      containers:
      - name: postgres
        image: postgres:9.6.5
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: psqldb-conf
              key: dbname
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: psqldb-conf
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psqldb-conf
              key: password