apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: kumar-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:     
    app: kumar-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: kumar-mysql
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kumar-mysql
  template:
    metadata:
      labels: 
        app: kumar-mysql
    spec:
      containers:
      - name: mysql 
        image: mysql:5.7 # image from docker-hub
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD # Setting Root Password of mysql From a 'Secret'
          valueFrom:
            secretKeyRef:
              name: mysqldb-credentials # Name of the 'Secret'
              key: root_password   # 'key' inside the Secret which contains required 'value'
        - name: MYSQL_USER # Setting USER username on mysql From a 'Secret'
          valueFrom:
            secretKeyRef:
              name: mysqldb-credentials
              key: username
        - name: MYSQL_PASSWORD # Setting USER Password on mysql From a 'Secret'
          valueFrom:
            secretKeyRef:
              name: mysqldb-credentials
              key: user_password
        - name: MYSQL_DATABASE # Setting Database Name from a 'ConfigMap'
          valueFrom:
            configMapKeyRef:
              name: mysqldb-conf
              key: name