apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "mongo-storage-class"