apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kumar-cluster-role
rules:
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kumar-cluster-role-binding
subjects:
- kind: User
  name: kumar # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kumar-cluster-role
  apiGroup: rbac.authorization.k8s.io