apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kumar-role
rules:
- apiGroups: [""]
  resources: ["pods","secrets"]
  verbs: ["list","get","watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kumar-role-binding
subjects:
- kind: User
  name: kumar # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: kumar-role
  apiGroup: rbac.authorization.k8s.io